name: Continue Configuration
version: 0.0.1
schema: v1
models:
  - name: Qwen 3.5 (9B)
    provider: ollama
    model: qwen3.5:9b
    apiBase: http://127.0.0.1:11434
    defaultCompletionOptions:
      stream: false
      contextLength: 4096